@startuml Simplified Sequence Diagram

Actor User as user  #MediumPurple
participant UI as ui
participant UserController as uc
participant RemoteCookbookAccess as rca 
participant "restserver/CookbookController" as rcc  
participant CookbookService as cs 
participant UserDataFilehandler as udf  
participant "UserData.json" as udj
participant "ui/CookbookController" as ucc 

user -> ui: Input password and username
activate user #LightBlue
activate ui #LightBlue
ui -> uc: signUp()
activate uc #LightBlue
uc -> rca: registerNewUser(username, password)
activate rca #LightBlue
rca -> rcc: HTTP POST(username, password)
activate rcc #LightBlue
rcc -> cs: checkIfUsernameTaken(username)
activate cs #LightBlue
cs -> udf: getUsers()
activate udf #LightBlue
udf -> udj: findUsers()
activate udj #LightBlue
udj --> udf: List<User>
deactivate udj
udf --> cs: List<User>
deactivate udf
cs --> rcc: false
deactivate cs

rcc -> cs: signup(username, password)
activate cs #LightBlue
cs -> udf: signup(username, password)
activate udf #LightBlue
udf -> udj: signup()
activate udj #LightBlue
udj --> udf: User
deactivate udj
udf --> cs: User
deactivate udf
cs --> rcc: User
deactivate cs
rcc --> rca: User, HTTP OK (200)
deactivate rcc

rca --> uc: User
deactivate rca
uc -> uc: startApp(User)
uc -> ucc: initialize(User, Accesstype)
deactivate uc
activate ucc #LightBlue
ucc -> ui
ui -> user
deactivate ucc
deactivate ui
deactivate user

@enduml